server:
  port: 8080

spring: 
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/preword?serverTimeZone=UTF&CharacterEncoding=UTF-8
    username: root
    password: wjdtudel!@12
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: c:\\사용자\\aischool\\spring_uploaded_files
